/**
 * Vite plugin that automatically resolves CJS interop issues for third-party
 * app bundles.
 *
 * Problem: some npm packages (e.g. `use-sync-external-store`) ship only CJS
 * and internally `require("react")`.  When the app-builder marks `react` as
 * external (shell-provided via importmap), rolldown's CJS interop shim tries
 * to call `require("react")` at runtime in the browser — which fails.
 *
 * Solution: for packages whose CJS code is just a thin wrapper around React
 * hooks that React 19 provides natively, we replace the CJS import with a
 * virtual ESM module that re-exports from `react`.  This happens at build
 * time via `resolve.alias`, so the CJS code is never bundled.
 *
 * The mapping table below is intentionally small — only packages that are
 * (a) CJS-only, (b) thin wrappers around React internals, and (c) pulled in
 * by common transitive deps like react-i18next.
 */

const VIRTUAL_PREFIX = "\0tokimo:cjs-interop:";

/**
 * Default CJS → ESM shim mappings.
 * Key: import specifier to intercept.  Value: the ESM source to substitute.
 */
const DEFAULT_MAPPINGS = {
  "use-sync-external-store/shim": {
    names: ["useSyncExternalStore", "useSyncExternalStoreWithSelector"],
    source: 'react',
  },
};

function buildShimSource(mapping) {
  const lines = [
    `// Auto-generated by @tokimo/app-builder cjs-interop plugin.`,
    `// Re-exports React 19 built-in equivalents — no CJS, no polyfill.`,
  ];
  for (const name of mapping.names) {
    lines.push(`export { ${name} } from ${JSON.stringify(mapping.source)};`);
  }
  return lines.join("\n") + "\n";
}

/**
 * @param {Record<string, { names: string[], source: string }>} [mappings]
 *   Override the default mapping table.  Each key is an import specifier
 *   (e.g. `"use-sync-external-store/shim"`), and the value describes the
 *   named exports to re-export from `source` (e.g. `"react"`).
 */
export function cjsInteropPlugin(mappings = DEFAULT_MAPPINGS) {
  /** @type {Map<string, string>} specifier → shim source */
  const shimCache = new Map();
  for (const [spec, mapping] of Object.entries(mappings)) {
    shimCache.set(spec, buildShimSource(mapping));
  }

  return {
    name: "tokimo:cjs-interop",
    enforce: "pre",

    resolveId(source) {
      if (shimCache.has(source)) {
        return VIRTUAL_PREFIX + source;
      }
      return null;
    },

    load(id) {
      if (id.startsWith(VIRTUAL_PREFIX)) {
        const spec = id.slice(VIRTUAL_PREFIX.length);
        return shimCache.get(spec) ?? null;
      }
      return null;
    },

    config(config) {
      const aliases = Object.fromEntries(
        [...shimCache.keys()].map((spec) => [spec, VIRTUAL_PREFIX + spec]),
      );
      return {
        resolve: {
          alias: {
            ...aliases,
            ...(config.resolve?.alias ?? {}),
          },
        },
      };
    },
  };
}
