/**
 * Vite plugin that automatically resolves CJS interop issues for third-party
 * app bundles.
 *
 * Problem: some npm packages (e.g. `use-sync-external-store`) ship only CJS
 * and internally `require("react")`.  When the app-builder marks `react` as
 * external (shell-provided via importmap), rolldown's CJS interop shim tries
 * to call `require("react")` at runtime in the browser — which fails.
 *
 * Solution: for packages whose CJS code is just a thin wrapper around React
 * hooks that React 19 provides natively, we replace the CJS import with a
 * virtual ESM module.  This happens in resolveId/load with exact specifier
 * matching, so sibling subpaths are not accidentally rewritten.
 *
 * The mapping table below is intentionally small — only packages that are
 * (a) CJS-only, (b) thin wrappers around React internals, and (c) pulled in
 * by common transitive deps like react-i18next.
 */

const VIRTUAL_PREFIX = "\0tokimo:cjs-interop:";

/**
 * Default CJS → ESM shim mappings.
 * Key: import specifier to intercept.  Value: the ESM source to substitute.
 */
const DEFAULT_MAPPINGS = {
  "use-sync-external-store/shim": {
    names: ["useSyncExternalStore"],
    source: 'react',
  },
  "use-sync-external-store/shim/with-selector": {
    code: buildWithSelectorShimSource(),
  },
  "use-sync-external-store/shim/with-selector.js": {
    code: buildWithSelectorShimSource(),
  },
};

function buildShimSource(mapping) {
  if (mapping.code) return mapping.code;

  const lines = [
    `// Auto-generated by @tokimo/app-builder cjs-interop plugin.`,
    `// Re-exports React 19 built-in equivalents — no CJS, no polyfill.`,
  ];
  for (const name of mapping.names) {
    lines.push(`export { ${name} } from ${JSON.stringify(mapping.source)};`);
  }
  lines.push(
    `import { ${mapping.names.join(", ")} } from ${JSON.stringify(mapping.source)};`,
    `export default { ${mapping.names.join(", ")} };`,
  );
  return lines.join("\n") + "\n";
}

function buildWithSelectorShimSource() {
  return `// Auto-generated by @tokimo/app-builder cjs-interop plugin.
// ESM equivalent of use-sync-external-store/shim/with-selector for React 19.
import { useDebugValue, useEffect, useMemo, useRef, useSyncExternalStore } from "react";

const objectIs = typeof Object.is === "function"
  ? Object.is
  : (x, y) => (x === y && (x !== 0 || 1 / x === 1 / y)) || (x !== x && y !== y);

export function useSyncExternalStoreWithSelector(
  subscribe,
  getSnapshot,
  getServerSnapshot,
  selector,
  isEqual,
) {
  const instRef = useRef(null);
  let inst;
  if (instRef.current === null) {
    inst = { hasValue: false, value: null };
    instRef.current = inst;
  } else {
    inst = instRef.current;
  }

  const [getSelection, getServerSelection] = useMemo(() => {
    let hasMemo = false;
    let memoizedSnapshot;
    let memoizedSelection;

    const memoizedSelector = (nextSnapshot) => {
      if (!hasMemo) {
        hasMemo = true;
        memoizedSnapshot = nextSnapshot;
        const nextSelection = selector(nextSnapshot);
        if (isEqual !== undefined && inst.hasValue) {
          const currentSelection = inst.value;
          if (isEqual(currentSelection, nextSelection)) {
            memoizedSelection = currentSelection;
            return currentSelection;
          }
        }
        memoizedSelection = nextSelection;
        return nextSelection;
      }

      const currentSelection = memoizedSelection;
      if (objectIs(memoizedSnapshot, nextSnapshot)) return currentSelection;

      const nextSelection = selector(nextSnapshot);
      if (isEqual !== undefined && isEqual(currentSelection, nextSelection)) {
        memoizedSnapshot = nextSnapshot;
        return currentSelection;
      }

      memoizedSnapshot = nextSnapshot;
      memoizedSelection = nextSelection;
      return nextSelection;
    };

    const maybeGetServerSnapshot = getServerSnapshot === undefined ? null : getServerSnapshot;
    return [
      () => memoizedSelector(getSnapshot()),
      maybeGetServerSnapshot === null
        ? undefined
        : () => memoizedSelector(maybeGetServerSnapshot()),
    ];
  }, [getSnapshot, getServerSnapshot, selector, isEqual]);

  const value = useSyncExternalStore(subscribe, getSelection, getServerSelection);
  useEffect(() => {
    inst.hasValue = true;
    inst.value = value;
  }, [inst, value]);
  useDebugValue(value);
  return value;
}

export default { useSyncExternalStoreWithSelector };
`;
}

/**
 * @param {Record<string, { names?: string[], source?: string, code?: string }>} [mappings]
 *   Override the default mapping table.  Each key is an import specifier
 *   (e.g. `"use-sync-external-store/shim"`), and the value describes either
 *   named exports to re-export from `source`, or full ESM `code`.
 */
export function cjsInteropPlugin(mappings = DEFAULT_MAPPINGS) {
  /** @type {Map<string, string>} specifier → shim source */
  const shimCache = new Map();
  for (const [spec, mapping] of Object.entries(mappings)) {
    shimCache.set(spec, buildShimSource(mapping));
  }

  return {
    name: "tokimo:cjs-interop",
    enforce: "pre",

    resolveId(source) {
      if (shimCache.has(source)) {
        return VIRTUAL_PREFIX + source;
      }
      return null;
    },

    load(id) {
      if (id.startsWith(VIRTUAL_PREFIX)) {
        const spec = id.slice(VIRTUAL_PREFIX.length);
        return shimCache.get(spec) ?? null;
      }
      return null;
    },

  };
}
